create table public.documents (
                                  id bigint generated by default as identity not null,
                                  url text null,
                                  owner_id uuid null default auth.uid (),
                                  created_at timestamp with time zone not null default now(),
                                  project_id bigint null,
                                  constraint documents_pkey primary key (id),
                                  constraint documents_project_id_fkey foreign KEY (project_id) references projects (id) on delete CASCADE
) TABLESPACE pg_default;
