create table public.projects (
                                 id bigint generated by default as identity not null,
                                 active boolean not null default false,
                                 address text null,
                                 name text not null,
                                 owner_id uuid not null,
                                 created_at timestamp with time zone not null default now(),
                                 type text null,
                                 contractor_id bigint null,
                                 customer_id bigint null,
                                 constraint projects_pkey primary key (id),
                                 constraint projects_contractor_id_fkey foreign KEY (contractor_id) references contractors (id) on delete set null,
                                 constraint projects_customer_id_fkey foreign KEY (customer_id) references customers (id) on delete set null,
                                 constraint projects_owner_id_fkey foreign KEY (owner_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists projects_owner_id_idx on public.projects using btree (owner_id) TABLESPACE pg_default;
