create table public.contractors (
                                    id bigint generated by default as identity not null,
                                    name text null,
                                    inn text null,
                                    email text null,
                                    phone text null,
                                    confirmed boolean null default false,
                                    owner_id uuid null default auth.uid (),
                                    created_at timestamp with time zone not null default now(),
                                    constraint contractor_pkey primary key (id)
) TABLESPACE pg_default;
