create table public.tasks (
                              id bigint generated by default as identity not null,
                              title text null,
                              description text null,
                              executor text null,
                              photos jsonb null,
                              control timestamp with time zone null,
                              owner_id uuid null default auth.uid (),
                              created_at timestamp with time zone not null default now(),
                              project_id bigint null,
                              type text not null default 'task'::text,
                              status text not null default 'do'::text,
                              priority text not null default 'medium'::text,
                              constraint problems_pkey primary key (id),
                              constraint tasks_project_id_fkey foreign KEY (project_id) references projects (id) on delete CASCADE
) TABLESPACE pg_default;
