create table public.gallery (
                                id bigint generated by default as identity not null,
                                url text null,
                                owner_id uuid null default auth.uid (),
                                created_at timestamp with time zone not null default now(),
                                task_id bigint null,
                                project_id bigint null,
                                constraint gallery_pkey primary key (id),
                                constraint gallery_project_id_fkey foreign KEY (project_id) references projects (id) on delete CASCADE,
                                constraint gallery_task_id_fkey foreign KEY (task_id) references tasks (id) on delete CASCADE
) TABLESPACE pg_default;
